- .github/workflows/main.yml
- Dockerfile
Before merging to master:
After merging to master:
> Upgrade to v2 e2e test framework.

- .github/workflows/main.yml
Each time a new Krill repo branch is made that changes something that depends on a modification in the E2E test framework in the rpki-deploy repo the Krill `main.yml` file has to be temporarily changed in the PR to reference a corresponding branch in the rpki-deploy repo, and changed back before the PR merges (thus breaking the E2E test in the PR checks report).
This change attempts first to checkout the E2E test framework from a branch by the same name as the current Krill branch, and only if that fails checkout the master E2E test framework branch.
> Use matching E2E test framework branch if exists

- .github/workflows/ci.yml
- .github/workflows/main.yml
This will prevent wasted executions of the matrix CI builds.
> Only run the CI build on Krill code changes.

- tests/e2e/simple_rp_roa_test.py
Depends on https://github.com/NLnetLabs/rpki-deploy/pull/23.
> Remove explicit service version detection, this is now handled by the e2e test framework instead.

- Dockerfile
Same fix as proposed for Routinator in https://github.com/NLnetLabs/routinator/pull/277.
I'm not sure if `krill` needs this but certainly `krillc` when run via this container needs it.
The "proper" fix is to handle the signal sent to the process, though Tini also handles other "pid 1" responsibilities as well (e.g. reaping finished background processes).
> Enable support for CTRL-C from outside the container.

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/pkg.yml
- .rpm/krill.spec
- Cargo.lock
- Cargo.toml
- debian/assets/krill.service.ubuntu1604
- debian/assets/krill.service.ubuntu1804
- debian/assets/krill.service.ubuntu2004
- debian/description.txt
- debian/scripts/postinst
- debian/scripts/postrm
- debian/scripts/prerm
- doc/krill.1
- doc/krillc.1
- Builds for Ubuntu 16.04, 18.04, 20.04 and Debian 9 and 10.
- Includes basic man pages for `krill` and `krillc`.
- Creates a krill user and a systemd (disabled) service with a krill config file generated by `krillc config simple` but with `log_type=syslog` and a generated token.
- Assumes that the target system has ca-certificates installed already.
- Vendor OpenSSL to support Ubuntu 16.04 which only has OpenSSL 1.0.0.
- Use GH caching to avoid repeat compilation of unchanging cargo deb and krill dependencies.
- Build in Docker containers as GH runners have too many non-standard packages and libraries pre-installed.
- Sanity check the created DEB in targeted O/S versions via LXC/LXD containers (for systemd support).
> Create a Krill DEB package via GH actions (#19)

- .github/workflows/pkg.yml
- Cargo.toml
These GitHub Actions Workflow changes ensure that packages for different releases of the same O/S (e.g. Debian or Ubuntu) are unique in their name/version/arch triple, as required by [Debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version) and enforced by [Aptly](http://aptly.info/) when managing a conforming repo.
Without these changes we cannot store the different flavours of Krill DEB that we produced on master for Krill v0.7.1 in a policy compliant APT repo server as the triples of the 5 different packages (Ubuntu 16.04/18.04.20.04 and Debian 9/10) are all the same. These physically cannot be stored in a policy compliant repo because the packages are stored by unique triplet in a common 'pool' directory irrespective of which 'distribution' they are …
> Proper pkg naming

- Cargo.toml
Without license-file the generated copyright file does not contain a "verbatim copy of its copyright information" as per https://www.debian.org/doc/debian-policy/ch-docs.html#copyright-information.
> Make the .deb copyright file compliant with Debian Policy.

- src/constants.rs
- src/daemon/http/server.rs
Note: also changes the initialisation of the `KRILL_VERSION` constant to use Cargo compile-time environment variable [`CARGO_PKG_VERSION`](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) because then using the similar `_MAJOR`, `_MINOR` and `_PATCH` compile-time env vars is easy.
The alternative is to use something like [`std::sync::Once` ](https://doc.rust-lang.org/std/sync/struct.Once.html) and [`semver_parser::version::parse()`](https://docs.rs/semver-parser/0.9.0/semver_parser/version/fn.parse.html) which is overkill when the values are available during compilation as Cargo env vars AND that removes the need to manually keep the constant in sync with the Cargo.toml version key value.
With this PR the following metric …
> Expose Krill server major.minor.patch version as gauge metrics

- .github/workflows/pkg.yml
- Cargo.lock
- Cargo.toml
- debian/scripts/postinst
- debian/scripts/postrm
- debian/scripts/prerm
- doc/krillc.1
- src/constants.rs
Correctly handle dashes in the Krill version number so that 'pre-release' 'tags' appended to the version number do not cause the package to be considered newer than a final untagged version number.
> Support 'pre-release' build labels in .deb packages

- doc/openapi.yaml
These couple of issues in the openapi specification were found when we used the [openapi-generator](https://github.com/openapitools/openapi-generator/) to generate client code to interact with the Krill REST API.
The `/bulk/cas/sync/parent` path on the server side is defined in [src/daemon/http/server.rs](https://github.com/NLnetLabs/krill/blob/ef7274bd73a8e24bf8c1732f06905fbca273bd06/src/daemon/http/server.rs#L546).
The issue with the ASN was found when we tried to make modifications to authorizations through the API. Krill won't accept ASNs provided as JSON strings, most likely due to the [AsNumber](https://github.com/NLnetLabs/krill/blob/ef7274bd73a8e24bf8c1732f06905fbca273bd06/src/commons/api/roas.rs#L613) type define in (RoaDefinition)[https://github.com/NLnetLabs/krill/blob/ef7274bd7 …
> Small fixes for the openapi specification

- .github/workflows/ci.yml
Without this we only run tests that are hidden behind the `functional-tests` and `ui-tests` feature flags when also enabling the `multi-user` feature flag. As the `multi-user` feature code makes (in theory non-breaking) changes to the authenticate and authorisation logic in Krill, and as these tests help validate the version of the code that most users will run (especially those who use a binary release such as the Docker image or DEB package as then the feature set is predetermined and cannot be changed), it would be good to make sure we run them before we release this branch.
Note: while most of the tests in the `ui-tests` feature are only enabled if the `multi-user` feature is also active, there is one UI test for the master token mode which is worth running even if the `multi-user` …
> Run functional and UI tests in non-multi-user mode

- defaults/aliases.polar
- defaults/roles.polar
- defaults/rules.polar
- doc/policies/team-based-access-control.polar
- src/daemon/auth/authorizer.rs
- src/daemon/auth/common/mod.rs
- src/daemon/auth/common/permissions.rs
- src/daemon/auth/mod.rs
- src/daemon/auth/policy.rs
- src/daemon/ca/server.rs
- src/daemon/http/server.rs
Use strongly typed permissions in the policy rules to ensure that rules cannot be written that reference non-existent permissions or to catch typos early, e.g. CA_CEATE instead of CA_CREATE. This also creates a single location in which the set of supported permissions is defined (`Permissions.rs`) instead of the set of supported permissions being defined by various static string references sprinkled across the code.
> Use strongly typed permissions in policy rules.

- Cargo.lock
- Cargo.toml
- tests/ui/mod.rs
Krill tests that drive the UI do so via a Docker container instance of the Cypress test runner and headless Chrome browser.
Unfortunately, if CTRL-C is pressed while `cargo test` is running the test suite is stopped but the Docker container keeps running.
Use a CTRL-C handler to issue a `docker kill` command if the test is aborted while running so that we don't leave the container running.
> Stop Cypress when UI test is aborted

- src/test.rs
When not running from a test a startup failure in Krill is logged by `fn main()`, but when run from a test such errors are lost. This change detects and logs them.
> Trap startup error in tests

- src/commons/actor.rs
- src/daemon/auth/common/permissions.rs
- src/daemon/http/mod.rs
Sometimes when investigating an Oso policy problem you need to know which type was passed to the rule engine, not just the display value of that type. This change logs the Debug representation of the types passed when trace level logging is enabled.
> Log types passed to oso when trace is enabled

- src/daemon/auth/authorizer.rs
- src/daemon/auth/providers/openid_connect/provider.rs
- tests/ui/cypress/specs/multi_user_openid_connect.js
- tests/ui/openid_connect_mock.rs
When logging in to an OpenID Connect provider via a 3rd party login form, the URL to which the user is HTTP redirected contains security features including a so-called CSRF token query parameter called `state`.
After the login form has been submitted and accepted by the 3rd party provider the provider redirects the end user back to Krill via their user agent (aka browser). This second redirect also includes a `state` query parameter and its value should be the same as that generated by Krill when the initial redirect URL is generated.
Prior to this PR the state value was generated per login request but was not checked upon receiving the redirect from the 3rd party provider. This PR:
- Adds a short lived secure Set-Cookie HTTP header to the initial redirect to the 3rd party login form, …
> Check the OpenID Connect CSRF token (resolves #383).

- doc/openapi.yaml
- docker/entrypoint.sh
- src/daemon/krillserver.rs
- tests/e2e/data.py
- tests/e2e/simple_rp_roa_test.py
(depends on [rpki-deploy PR #28](https://github.com/NLnetLabs/rpki-deploy/pull/28))
- OpenAPI YML corrections.
- Support the new way to activate the TA (in the Krill Docker image).
- FIX: Include the correct ta.cer URI in the TAL.
- Use two seprarate Python libraries for Krill: one for CA REST SAPIs and one for PUB REST APIs.
- FIX: Test for the actual CAs and resources to create, as the presence of the testbed CA violates the previous check assumptions.
- FIX: Resource ASN, v4 and v6 values can no longer be assumed to have the same sort order as when given to Krill.
- Factor out test suite code into helper functions for better readability and maintainability.
- Retry RTR fetching (needed for ROAs obtained from Rcynic Lihttpd server served JSON as otherwise connecting too early results in …
> Improvements and fixes for e2e testing on the Krill dev branch

- src/daemon/mq.rs
There was an optimisation to not synchronise with a repo, or parent, when it was already scheduled.
But it seems that this can lead to race conditions, especially on slow (virtual) hardware. Doing the synchronisation too often does not hurt, so this change just removes this optimisation.
> Schedule parent/repo syncs even if there is another sync on the queue (#445)

- .github/workflows/e2e.yml
If there's no e2e framework branch for our branch, check if there is an e2e framework branch for our base branch before falling back to master.
> Try harder to use the right e2e framework branch

- Cargo.lock
- Cargo.toml
- defaults/rules.polar
- doc/policies/team-based-access-demo.polar
- src/daemon/auth/providers/openid_connect/jmespathext.rs
Checked versions to be updated and ran `cargo update`. This leaves only 4 warnings for `cargo audit`.
We should plan to upgrade hyper, reqwest, tokio, bytes, rpki-rs and bcder in a future release. But for the moment there are no pressing security or functional reasons to do so and this is a significant amount of work (e.g. the inbound HTTPS connections). So, in short - I believe that this is enough for 0.9.0-rc1
> Ran cargo update (#366)

- src/daemon/auth/providers/openid_connect/jmespathext.rs
This PR fixes a problem with JMESPath matching when using the custom `resub()` function with null input.
Prior to this PR this causes `resub()` to abort with an error. However, resub should return its input unchanged if there is no match to substitute, and null is a useful input to support when `resub()` is chained with another JMESPath expression.
For example, given this `krill.conf` fragment:
```
[auth_openidconnect.claims]
admin_role = { jmespath="resub(groups[?@ == '0bbdc586-e843-44e4-aece-a47ef113a2a0'] | [0], '^.+$', 'admin')", dest="role" }
readonly_role = { jmespath="resub(groups[?@ == '4d85e06b-2e0d-4554-b0bd-bf6030462f00'] | [0], '^.+$', 'readonly')", dest="role" }
```
Prior to this PR if the specified "admin" group is present in the users OpenID Connect claims but the …
> Return null instead of an error on null input to JMESPath fn resub().

- src/commons/error.rs
- src/daemon/ca/certauth.rs
- tests/migrate_repository.rs
As it turns out - this was broken earlier because of a failure to republish objects during a key roll during 0.9.0 development - fixed in issue #509 prior to the 0.9.0 release.
Note, there is a remaining - unrelated - issue that can lead to long running tests. The background job scheduler is based on 'clokwerk' and lives in runtime of its own (hiding async stuff). This can lead to the scheduler continuing to run for up to two minutes when the test (functional.rs) is being torn down. We should re-investigate the schedular in future - this is also relevant when we want to look at multi active-node clustering.
> Migrate CA repository using key rollover (#480)

- src/daemon/ca/rc.rs
- tests/functional.rs
I.e. ROAs will be re-created when a parent is removed and re-added.
> Create ROAs if needed, when keys are activated (#601)

- src/cli/client.rs
- src/cli/options.rs
- src/cli/report.rs
- src/commons/api/ca.rs
- src/commons/util/httpclient.rs
- src/constants.rs
- src/daemon/ca/manager.rs
- src/daemon/ca/status.rs
- src/daemon/http/mod.rs
- src/daemon/http/server.rs
- src/daemon/krillserver.rs
This PR adds the function to monitor child CA connections. The stats are kept outside of the CA state in the existing structure that we have in order to avoid churn in the parent CA. The stats include the last connection time, result and user agent of the child CA.
Furthermore Krill CAs will now send their version in the user agent when sending RFC 6492 or 8181 protocol messages to their parents and publication server. See issue: #620
> Monitor krill versions

- .github/workflows/pkg.yml
Temporary workaround for https://github.com/cat-in-136/cargo-generate-rpm/issues/21.
> Patch workflow for cargo-generate-rpm issue #21 (#613)

- Cargo.lock
- Cargo.toml
- src/commons/api/aspa.rs
- src/commons/util/dummysigner.rs
- src/daemon/ca/events.rs
- tests/functional.rs
This updates the logic to allow for an empty provider AS set (as per sidrops discussion). Tests were added, and an issue was found in the encoding of empty provider as sets, which was fixed in this PR for rpki-rs:
https://github.com/NLnetLabs/rpki-rs/pull/171
> Support ASPAs with an explicit empty provider as set.

- src/commons/util/ext_serde.rs
- src/daemon/auth/common/crypt.rs
Fixes #751.
I'm not sure if this is the _right_ way to fix this, but it seems to work.
Tested on my Raspberry Pi 4b by cross compiling on my x86_64 laptop host then running the produced binary with config-file users on the Pi:
```
$ cargo install cross
$ rustup target add armv7-unknown-linux-gnueabihf
$ cross build --target armv7-unknown-linux-gnueabihf --features static-openssl --release
$ scp target/release/krill pi@192.168.0.18:
$ scp target/release/krillc pi@192.168.0.18:
$ ssh pi@192.168.0.18
$ ./krillc config user --id x18
Enter the password to hash: 
***
[auth_users]
"x18" = { attributes={ role="admin" }, password_hash="********", salt="********" }
$ grep -Ev '^#' krill.conf | sed '/^\s*$/d'
log_level = "trace"
log_type = "stderr"
admin_token = "********"
service_uri = …
```
> Fix compilation on armv7-unknown-linux-gnueabihf by supplying missing Serde impls. (#751)

- .github/workflows/pkg.yml
- Cargo.toml
- pkg/common/krill-debian-buster-aarch64-unknown-linux-gnu.krill.service
Passed basic sanity tests on a ROCK64 AARCH64 device running Debian Buster.
Builds on the previous PR adding ARMv7 on Debian 11 support.
Merge #755 first then this PR will update to target the `main` branch and the packaging action will then run.
> Initial support for AARCH64 on Debian 10 Buster

- src/commons/actor.rs
Silence multi-user related dead code warnings about fields that are written to but not read unless the multi-user feature is enabled. 
This typically occurs when disabling default features while developing to speed up compilation and then you get these annoying warnings. We don't exclude the fields entirely from the compilation because that would add more conditional compilation guards which makes the code harder to read.
> Silence multi-user related dead code warnings.

- .github/workflows/pkg.yml
> We use `-dev` as the next version label now, not `-bis`.

- .github/workflows/pkg.yml
Make the same change as was made for Routinator. See: https://github.com/NLnetLabs/routinator/pull/688/commits
The packaging workflow has been triggered manually against this PR branch. The output of the run can be seen [here](https://github.com/NLnetLabs/krill/actions/runs/1791494894). This won't work until PR https://github.com/NLnetLabs/krill/pull/767 has first been merged and this PR branch then synced with main.
> Attribute the DEB changelog entry to RPKI team

- Cargo.lock
- Cargo.toml
- README.md
- src/commons/remote/rfc8181.rs
Makes krill more liberal in accepting an RFC 8181 Error Response that is lacking the tag attribute. As reportedly can  happen under apnic at the moment.
> V0.9.5 rc8 prep

- .github/workflows/pkg.yml
- Cargo.toml
- pkg/common/krill-ubuntu-jammy.krill.service
As the 20.04 .deb doesn't work on 22.04 due to a libssl mismatch.
> Package Krill for Ubuntu 22.04 Jammy Jellyfish

- Cargo.lock
- Cargo.toml
- README.md
No new functionality, only security fixes in upstream dependencies of the crate which were detected by GitHub Dependabot.
> Upgrade KMIP dependencies.

- README.md
- src/commons/crypto/signing/signers/pkcs11/context.rs
- src/commons/crypto/signing/signers/pkcs11/signer.rs
This PR modifies Krill to be able to connect to and use the HSM in certain transient failure scenarios without a restart of Krill as is currently required.
Firstly, we re-initialize the PKCS#11 context in order to "flush" the cache of some PKCS#11 libraries so that they notice an unavailable token becoming available without needing to restart Krill. (see: https://github.com/parallaxsecond/rust-cryptoki/issues/75). This was previously implemented when the `pkcs11` crate was used but was temporarily removed as it didn't work as was once we switched to the `cryptoki` crate. The `cryptoki` crate since added the required functionality so that we can now re-implement this.
This PR also changed some of the error codes considered to be permanent failures to instead be considered transient …
> Handle more PKCS#11 transient failure scenarios. 

- Cargo.lock
- README.md
This PR updates the `cryptoki-sys` crate to v0.1.4 which includes PKCS#11 bindings for the x86_64-unknown-freebsd Rust target, to address issue #861.
This is a DRAFT PR as the v0.1.4 release of `cryptoki-sys` is not available yet, but is expected soon. See https://github.com/parallaxsecond/rust-cryptoki/pull/96.
> PKCS#11 HSM support should compile out-of-the-box on FreeBSD.

- Dockerfile
Since PR #773 was merged 10 days ago to `main` the `Dockerfile` can only be built using the [BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/) mode of Docker (i.e. running `DOCKER_BUILDKIT=1 docker build` instead of plain `docker build`. This is a regression that was introduced some time during the development of PR #773 and clearly a plain `docker build` test was not done using the resulting `Dockerfile` which was my mistake.
The `MODE` and support for BuildKit were added for use by the GitHub Actions `pkg` workflow to support cross compilation and building of multiple Docker images in parallel, some with externally pre-cross compiled binaries to be copied into the image, others building the binaries within the image building process. The copy `MODE` is not …
> Fix `docker build` for normal (aka non-CI) users

- src/commons/crypto/signing/signers/kmip/signer.rs
Focus on the lacking support, rather than seeming to ignore the server when in fact trying it anyway.
I toyed with different error and warning messages but decided that when in force mode the fact that this is then a warning only is enough to signal to the operator that this is not an error (at least not at this point, an error will occur later if the KMIP server really does lack the required support rather than just falsely claiming that it does).
> Improve KMIP lacking support log messages (#889)

- .github/workflows/pkg.yml
- Dockerfile
- README.md
This PR is a first step in extending the Routinator workflow to use the same multi-architecture Docker image support that Krill has.
The purpose of this PR is to reduce the number of differences between the Routinator and Krill `pkg` workflows to benefit from best practices in both projects where changes were made only to one but not the other or vice versa, and to reduce the number of changes that have to be made when extending the Routinator `pkg` workflow to support mutli-arch Docker images (along with the other changes that entails).
No actual changes in behaviour should occur because of this PR, changes are either cosmetic or for consistency but have no unwanted effects on the end result.
> Cross project pkg workflow consistency

- src/cli/client.rs
- src/cli/options.rs
- src/test.rs
Essentially this is just replacing `uri::Https` with `idexchange::ServiceUri` (both from `rpki-rs) as the latter allows both http and https.
> Allow plain HTTP for --server in krillc. #913

- README.md
- src/upgrades/pre_0_10_0/pubd_migration.rs
Note: testing this is quite awkward because of the complicated way that is used to determine what migrations are needed.
A better fix would be to simplify that logic. I believe that the proper change would be too involved for a quick bug fix release, so this current change is just a quick fix. I created issue #929 so that we can do this properly for release 0.11.0.
> Do not skip migration of pubd 0.9.0 (fix: 928)

- src/pubd/repository.rs
- src/upgrades/pre_0_9_0/pubd_objects_migration.rs
Added to the repo stats endpoint (/stats/repo). Example output:
```
{
"publishers": {
"testbed": {
"objects": 3,
"size": 3762,
"manifests": [
{
"uri": "rsync://localhost/repo/testbed/0/217876AA966B965A6EDFDED43C469B90ED11AC6D.mft",
"this_update": "2022-09-13T15:10:12Z",
"next_update": "2022-09-14T18:18:12Z"
}
]
},
"ca": {
"objects": 5,
"size": 8247,
"manifests": [
{
"uri": "rsync://localhost/repo/ca/0/CC2487CF3A9C774BFAE2DCE4DD8368441C75C720.mft",
"this_update": "2022-09-13T15:10:12Z",
"next_update": "2022-09-14T16:01:12Z"
}
]
},
"ta": {
"objects": 3,
"size": 3663,
"manifests": [
{
"uri": "rsync://localhost/repo/ta/0/0A6EA673F04AAA345D605A38E7710A2D8413B56C.mft",
"this_update": "2022-09-13T15:10:12Z",
"next_update": "2022-09-14T17:02:12Z"
}
]
}
},
"session": …
```
> Show repo init settings

- src/daemon/ca/manager.rs
- src/daemon/krillserver.rs
- src/daemon/scheduler.rs
- src/pubd/manager.rs
With these changes CAs with a local publication server should bypass HTTPS and CMS for RFC 8181 (publication) and this should result in a hopefully big performance improvement.
Automated tests are okay. Will now build a package and try it in our test VMs.
> Local publishing without HTTPS/CMS #935

- Cargo.lock
- Cargo.toml
- defaults/krill-pubd.conf
- defaults/krill-testbed.conf
- defaults/krill.conf
- src/daemon/config.rs
- src/daemon/http/server.rs
- src/daemon/scheduler.rs
- test-resources/krill-init-multi-user.conf
- test-resources/krill-init.conf
Allows optional configuration of multiple `ips` but will not change default behaviour and will still accept `ip` if it was set.
This will allow Krill to listen on both IPv4 and IPv6, of multiple of either of course..
Internally the code was reworked a bit so that the futures do not return an error anymore.. they just log an error and come back. This was needed to make the wiring a bit more manageable.
> Support listening on multiple IP addresses. (#955)

- Cargo.lock
- Cargo.toml
- README.md
- src/daemon/ca/manager.rs
- src/daemon/mq.rs
- src/test.rs
- tests/remote_parent_and_repo.rs
There was a possible (very rare ~ 1 in 1000) race condition reported where seemingly a parent sync was not triggered if the repository was added *just* after the parent was added (same second timestamp). It's hard to see from the code how this could happen except if sync with the parent was ignored when the parent was added (because no repo was set), and adding the repo did not trigger a sync because the other sync was still pending.
In any case in this RC we make some changes that will hopefully prevent this issue, or at least improve logging if it does happen:
- do not trigger sync with parent if the repo is not yet configured
- do not ignore repo not set when syncing with a parent - error will trigger rescheduling
- improve logging
- add explicit test for remote access
The test is good …
> Merge release 0.12.0-rc3

- .github/workflows/pkg.yml
Rather than pollute the org wide central repo with the reusable packaging workflow, it has been moved to its own home in a new ploutos repo. This change follows that move.
> Follow move of reusable pkg workflow to new ploutos repo.

- src/commons/eventsourcing/locks.rs
- src/commons/eventsourcing/mod.rs
- src/commons/eventsourcing/store.rs
- src/commons/eventsourcing/wal.rs
- src/test.rs
- tests/benchmark.rs
This change will ensure that locks are used for ``WalSupport``  types (write-ahead log) managed through the ``WalStore`` in the same way as we have been doing for ``Aggregate`` types managed trough the ``AggregateStore``.
This fixes an issue with concurrent creation of CAs as part of the (unreleased) ca_imports function.
> Use handle locks in WalStore.

- src/cli/client.rs
- src/cli/options.rs
- src/commons/api/admin.rs
- src/commons/api/ca.rs
- src/commons/api/rrdp.rs
- src/daemon/ca/publishing.rs
- src/daemon/http/server.rs
- src/daemon/krillserver.rs
- src/pubd/manager.rs
- src/pubd/repository.rs
- src/test.rs
- tests/migrate_repository.rs
[draft] Merge after #PR982
This adds functionality to purge (well, maybe it should be called remove? zap? obliterate?) content from the publication server repository by URI. This will help in case a repository got into a bad state because of issue #981. But it may also help in certain other cases.
To use this from the command line:
```
krillc help pubserver purge
krillc-pubserver-purge 
Delete specific files from the Publication Server
USAGE:
krillc pubserver purge [FLAGS] [OPTIONS] --base_uri <rsync URI>
FLAGS:
--api        Only show the API call and exit. Or set env: KRILL_CLI_API=1
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-u, --base_uri <rsync URI>    Remove file matching the base uri if it ends with '/', or the exact uri if it …
```
> Purge content by uri

- src/pubd/manager.rs
[draft] We should make a branch for `prep-0.12.2` and merge to that if this is stable.
This PR removes the RwLock in RepositoryManager.
We saw issues where a busy Krill Publication Server would freeze without any reported issues. We suspect that this may be due to a deadlock or lock starvation issue in RepositoryManager. A version where read locks were no longer acquired (they are actually not needed) - was deployed and so far seems stable.
Then one more commit was done to remove the RwLock altogether in this layer. It is in fact not needed because there are existing RwLocks in the layers below this (`WalStore::send_command`) to ensure that actual updates do happen sequentially.
> Remove RepositoryManager RwLock

- .github/workflows/ci.yml
- test-resources/pykmip/constraints.txt
Work around failing PyKMIP tests by pinning to an old SQLAlchemy Python package for use by PyKMIP.
The root issue was visible [in the PyKMIP logs](https://github.com/NLnetLabs/krill/actions/runs/4224858478/jobs/7336359491#step:8:2726):
```
2023-02-20 15:36:27,259 - kmip.server.engine - ERROR - QueuePool limit of size 5 overflow 10 reached, 
connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
```
> Constrain PyKMIP SQLAlchemy dependency version

- src/commons/api/rrdp.rs
- src/pubd/manager.rs
- src/pubd/repository.rs
- src/upgrades/mod.rs
- src/upgrades/pre_0_13_0/mod.rs
With this we no longer need to do an RRDP session reset after migration to 0.13.0. This will reduce the impact significantly on busy repositories.
In the process the code was reorganised a bit. Hopefully cleaner now.. in particular: in theory the same object could be published in multiple locations (names) by a publisher. It does not make sense to do so, but it's allowed by the spec. By using the URI as the object key instead of the hash this is now possible.
> No session reset on 0.13 upgrade

- Cargo.lock
Closed #1026 which is outdated and targeted main. There should be no issue merging this into prep-0.13.0 and including this in the next release, right?
> Update openssl dependency

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/commons/crypto/signing/dispatch/krillsigner.rs
- src/daemon/ca/keys.rs
nevermind.. the change I made that fxes this is actually in rpki-rs. Hold on..
> Enforce that id-ad-caRepository uses a trailing slash. (#1030)

- Cargo.toml
- src/cli/options.rs
Removes the compiler feature and enables support in the CLI for all. ASPA support was already enabled by default in the API. Following the last IETF it is unlikely that the object syntax will still change.
> Enable ASPA support (#1031)

- Cargo.toml
- pkg/common/krill-debian-bookworm.krill.service
- pkg/rules/packages-to-build.yml
- pkg/rules/packages-to-test.yml
Successful packaging test run can be seen here: https://github.com/NLnetLabs/krill/actions/runs/6318680912
> Pkg for Debian 12 Bookworm

- src/daemon/ca/manager.rs
- src/daemon/mq.rs
- src/daemon/scheduler.rs
- src/ta/proxy.rs
Krill now schedules renewal if the testbed is enabled on startup and again every /2 of the next update period. This is implicitly tested because of tests that use the testbed setup.
> Let testbed automatically renew TA manifest and CRL #1095

- Cargo.lock
- Cargo.toml
- src/commons/error.rs
- src/daemon/mq.rs
- src/daemon/scheduler.rs
Note that FatalError is only used for issues in using the storage. We can't recover from that.
If the storage issues are resolved and Krill restarts, it will also schedule any missing tasks. If that scheduling fails, then this is again a fatal error. This is by design. Someone should look at the issue.
> Crash Krill if a fatal error is encountered by the task scheduler.

- Cargo.lock
- Cargo.toml
We need this, otherwise getting an unknown CA would result in creating a scope for it.
> Upgrade to kvx that uses locks outside of scope dir.

- .github/workflows/ci.yml
Work around the backward incompatible Python removal of deprecated `ssl.wrap_socket()` function which breaks PyKMIP (as there is no newer version of PyKMIP to upgrade to which would follow the change in Python).
From: https://docs.python.org/3/whatsnew/3.12.html#ssl
> Remove the ssl.wrap_socket() function, deprecated in Python 3.7
> Pin Python to version compatible with PyKMIP.

- .github/workflows/ci.yml
To work around GHA warning:
> The following actions uses node12 which is deprecated and will be forced to run on node16: <snip>. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> Bump GH Actions action versions.

- src/daemon/ca/status.rs
Cherry-picked the commit from #1164, but that was branched off work we decided to drop. #1164 was discussed and aproved, so I will just merge this now.
> Ignore corrupt status files and use default.

- Cargo.lock
- Cargo.toml
- README.md
This PR upgrades the Krill KVX dependency from v0.9.2 to v0.9.3 to fix Krill issue #1171.
> Upgrade KVX dependency to fix #1171.

- Cargo.lock
- README.md
> Don't use dependency versions that cause warnings.

- .github/workflows/pkg.yml
- Cargo.lock
- Cargo.toml
- README.md
A successful run of the upgraded `pkg` workflow can be seen here:
https://github.com/NLnetLabs/krill/actions/runs/8605626059
Summary of changes in Ploutos since the current v6.3.1 that Krill is using now:
[v7.3.0](https://github.com/NLnetLabs/ploutos/releases/tag/v7.3.0)
This release contains the following changes:
- Expose optional extra_cargo_deb_args arg for package_build_rules (https://github.com/NLnetLabs/ploutos/pull/100)
---
[v7.2.5](https://github.com/NLnetLabs/ploutos/releases/tag/v7.2.5)
This bug fix release contains the following changes:
- FIX: rpmlint: command not found (https://github.com/NLnetLabs/ploutos/issues/98).
---
[v7.2.4](https://github.com/NLnetLabs/ploutos/releases/tag/v7.2.4)
- Bump actions/github-script from 6 to 7 (https://github.com/NLnetLabs/ploutos/pull/93) …
> Upgrade pkg workflow from Ploutos v6 to v7.

- Cargo.toml
cryptoki itself is marked optional and only needed for hsm builds. cryptoki-sys is still compiled unconditionally, also in builds disabling the hsm feature. This causes build failures if cryptoki isn't installed or on systems unsupported by cryptoki-sys's build script.
> Make cryptoki-sys optional

- .gitignore
- src/cli/ta_client.rs
- src/commons/api/import.rs
- src/daemon/ca/manager.rs
- src/daemon/ca/publishing.rs
- src/daemon/krillserver.rs
- src/ta/common.rs
- src/ta/mod.rs
- src/ta/signer.rs
Allows overriding the initial manifest number, either by specifying `--initial_manifest_number` if the CLI is used to initialise the TA signer, or by including `ta_mft_nr_override: #nr` in the ImportTa JSON.
Allows overriding the TA manifest number when signing a TA proxy request by specifying `--ta_mft_number_override` in the CLI.
> Allow overriding the TA manifest number.

- src/commons/bgp/analyser.rs
This should fix the issue observed in #1177.
The code locked the 'seen' announcements while downloading new RIR dump files. This prevented read access to the announcement during download. This change postpones getting the write lock until after the download is completed, so it only keeps it for the shortest possible time.
> Fix locking when downloading RIS dump files (#1177)

- Cargo.lock
- Cargo.toml
- Changelog.md
This is just a reminder to require the latest release of rpki-rs when we release Krill.
Fixes #1195 via [rpki-rs#295](https://github.com/NLnetLabs/rpki-rs/pull/295).
> Switch to rpki-rs git main to pull in fix for empty CRLs.

- Cargo.lock
This updates the locked version of the h2 crate to 0.3.26 to fix [RUSTSEC-2024-0332](https://rustsec.org/advisories/RUSTSEC-2024-0332).
> [0.13] Upgrade locked h2 to 0.3.26.

- src/daemon/ca/certauth.rs
This PR adds a check whether the resource class exists before applying a “child revoke key” command. This fixes a crash where revoking a parent removed a resource class which then lead to children revoking keys for that now non-existing resource class. The change will cause to simply send an OK response to such requests.
> Don’t try to revoke child keys for non-existing resource classes.

- src/commons/crypto/signing/signers/pkcs11/signer.rs
This PR fixes a potential endless recursion when converting an error in the  PKCS11 signer.
> Fix an infinite recursion in PKCS11 error conversion.

- .github/workflows/ci.yml
- Cargo.toml
- src/commons/api/ca.rs
- src/commons/api/import.rs
- src/commons/crypto/signing/signers/pkcs11/signer.rs
- src/commons/eventsourcing/store.rs
- src/daemon/auth/common/session.rs
- src/daemon/auth/providers/openid_connect/provider.rs
- src/daemon/ca/certauth.rs
- src/daemon/ca/status.rs
- src/daemon/krillserver.rs
- src/pubd/repository.rs
- src/upgrades/mod.rs
This PR fixes all warnings from nightly Clippy as of today and enables a Clippy run in the CI workflow for the stable channel with all features enabled.
> Fix Clippy warnings and enable Clippy in CI.

- Cargo.toml
- src/cli/ta_client.rs
- src/commons/api/ca.rs
- src/commons/api/rrdp.rs
- src/commons/crypto/signing/misc.rs
- src/commons/crypto/signing/signers/kmip/signer.rs
- src/commons/crypto/signing/signers/pkcs11/signer.rs
- src/daemon/auth/common/crypt.rs
- src/daemon/ca/certauth.rs
- src/daemon/ca/manager.rs
- src/daemon/http/mod.rs
- src/daemon/http/server.rs
- src/pubd/repository.rs
- src/ta/proxy.rs
- src/ta/signer.rs
- src/upgrades/mod.rs
- src/upgrades/pre_0_10_0/cas_migration.rs
- src/upgrades/pre_0_10_0/old_events.rs
This PR upgrades the codebase to Rust edition 2021.
This mostly just means removing a number of use statements for `TryFrom` and `TryInto`. There are no actual code changes.
> Upgrade to edition 2021.

- src/daemon/auth/providers/openid_connect/provider.rs
Based on https://github.com/ramosbugs/openidconnect-rs/issues/152 and some discussions with @partim , it seems like the OpenID connect client does not automatically rediscover anything, leading to login loops when e.g. the JWKs are rolled (as the signature can no longer be verified).
```
2024-06-27 10:29:15 [WARN] OpenID Connect: ID token verification failed: Signature verification failed [additional info: caused by: Signature verification failed, caused by: No matching key found]
```
This PR adds an explicit lifetime to the connection, and if the connection has existed for more than 60 seconds, it will initialise a new client. This is a tradeoff between doing rediscovery on every request (so requesting the /.well-known/openid-configuration endpoint, the jwk_uri inside that, and then the …
> Create new client if old client is older than 60 s

- Cargo.toml
- doc/manual/source/install-and-run.rst
- pkg/common/krill-ubuntu-noble.krill.service
- pkg/rules/packages-to-build.yml
- pkg/rules/packages-to-test.yml
This PR adds support for Ubuntu Noble and removes support for Ubuntu 16.04, 18.04 and Debian 9.
> Add support for Ubuntu Noble and remove support for Ubuntu Xenial, Bionic, and Debian Stretch

- Cargo.lock
- Cargo.toml
- src/commons/crypto/signing/signers/pkcs11/context.rs
This PR removes the dependency on `once_cell` since all the relevant functionality is now in `std`.
> Replace once_cell::OnceCell with std::sync::OnceLock.

- Dockerfile
All the other projects seem to be on 3.21 - it probably makes sense for Krill to be as well.
> Update Docker Alpine to 3.21

- src/daemon/http/auth/authorizer.rs
- src/daemon/http/auth/providers/config_file.rs
- src/daemon/http/auth/providers/openid_connect/provider.rs
- src/daemon/http/auth/session.rs
- src/daemon/http/metrics.rs
- src/daemon/krillserver.rs
- src/daemon/mq.rs
- src/daemon/scheduler.rs
This PR moves sweeping the login session cache from being driven of the scheduler (and thus using persistent tasks) into a Tokio task that is spawned onto the runtime at the start of the daemon.
The PR is one step in separating Krill server core logic from the HTTP API logic.
> Move login cache sweep from scheduler into its own spawned task.

- .github/workflows/pkg.yml
- doc/manual/source/install-and-run.rst
- pkg/rules/packages-to-build.yml
- pkg/rules/packages-to-test.yml
Because we missed out on RHEL 9 last time round, let's make sure to not release a new version without support for the latest OS version.
> Add support for RHEL 10

- doc/manual/source/trust-anchor.rst
- src/api/ta.rs
- src/server/taproxy.rs
- tests/functional_old_data.rs
Result with a child request:
```
$ krillta proxy signer make-request
-------------------------------
nonce: 2a04a5c2-74e0-4316-9d18-786c5fe0e64b
-------------------------------
There is one child request
-------------------------------
child request
-------------------------------
child:         online
entitlements:  asn: 'AS0-AS4294967295', ipv4: '0.0.0.0/0', ipv6: '::/0'
key:           F038768DAD7A1CF068D28B32CDDF9525BDCF410F    (re-)issue
NOTE: Use the JSON output for the signer.
```
Result without a child request:
```
$ krillta proxy signer make-request
-------------------------------
nonce: 18da5ef5-20d2-4167-93a1-435ba475f29f
-------------------------------
There are no child requests
Certificates will be reissued 80 weeks before expiry.
The current certificate expires on …
```
> Make TA messaging clearer

- .github/workflows/pkg.yml
- Cargo.toml
- doc/manual/source/install-and-run.rst
- pkg/common/krill-debian-trixie.krill.service
- pkg/common/krill.krill.service
- pkg/rules/packages-to-build.yml
- pkg/rules/packages-to-test.yml
This PR adds support for Debian Trixie (13). It also cleans up some old references that are no longer used.
https://github.com/NLnetLabs/krill/actions/runs/16627049763/job/47047047601
> Add support for Debian Trixie
