- daemon/ui/src/App.vue
- daemon/ui/src/locales/en.json
- daemon/ui/src/locales/it.json
- daemon/ui/src/router.js
- daemon/ui/src/services/APIService.js
- daemon/ui/src/views/Login.vue
- daemon/ui/src/views/PublisherDetails.vue
- daemon/ui/src/views/Publishers.vue
- daemon/ui/yarn.lock
Add publisher, locale switching, form validation, dict for error messages, is_logged_in check
> Latest UI Changes

- .github/workflows/pkg.yml
See: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
> Run on branch or PR, not both

- Cargo.toml
(and restart after upgrade = true)
> Test minimal systemd Cargo.toml syntax

- Dockerfile
> Use an official Alpine docker image release rather than Alpine Edge.

- src/daemon/config.rs
Use log level comparison to disable logging "below" a certain level instead of handling each level explicitly. Added a test that checks the log level the log framework thinks has been set after configuring it from a given Krill log level setting.
> FIX: Don't log DEBUG level messages when log_level is set to 'info' (fixes #434).

- src/daemon/ca/certauth.rs
- src/upgrades/v0_9_0/ca_objects_migration.rs
- src/upgrades/v0_9_0/pubd_objects_migration.rs
Will just merge this, there are no logic changes except for a counter of migrated commands and some logging.
> Add progress logging for migrating commands (#503)

- src/commons/api/ca.rs
- src/daemon/ca/manager.rs
- src/daemon/ca/status.rs
- src/daemon/http/server.rs
- src/daemon/krillserver.rs
Builds on the other PR for monitoring ca-parent connections. Propose to merge into that, and then both to dev.
> Monitor ca to publication server connections with prometheus. (#650)

- Cargo.lock
- Cargo.toml
- src/commons/api/admin.rs
- src/commons/api/ca.rs
- src/daemon/ca/certauth.rs
- src/daemon/ca/manager.rs
- src/daemon/ca/status.rs
- src/daemon/config.rs
- src/daemon/krillserver.rs
- src/daemon/scheduler.rs
Would like to merge (after review) so we can test a new rc2 on testbed - even if we do not release it publicly.
> Ca status cache fixes

- pkg/debian/postinst
- pkg/rpm/postinst
Reported by @racompton, thanks!
> Restrict package generated krill conf perms

- Cargo.lock
- Cargo.toml
- README.md
- src/daemon/scheduler.rs
> Release 0.9.6 'Newer ROAs Please'

- Cargo.lock
- Cargo.toml
- README.md
- tests/testbed.rs
Fix #874 by upgrading to a new version of the `rpki` crate that correctly generates the affected XML.
> Upgrade rpki crate dependency (fixes #874).

- .github/workflows/ci.yml
> Bump pykmip-test from 18.04 to 20.04

- src/commons/crypto/signing/dispatch/krillsigner.rs
- src/commons/crypto/signing/dispatch/signerrouter.rs
Such as [this](https://github.com/NLnetLabs/krill/runs/7955242431?check_suite_focus=true#step:4:459) and [this](https://github.com/NLnetLabs/krill/runs/7955242431?check_suite_focus=true#step:4:466).
> Prevent unused variable warnings when default features are disabled.

- Cargo.lock
- Cargo.toml
- README.md
NOTE: This code currently depends on the unmerged and unreleased fix for this in rpki-rs. We need to have a new release of rpki-rs before this can be merged.
> Encode ranges as prefixes where possible #903

- Cargo.lock
- Cargo.toml
- README.md
- src/upgrades/pre_0_10_0/pubd_migration.rs
> Release 0.10.2

- Cargo.lock
- Cargo.toml
[draft] depends on rpki-rs 0.15.8-dev on GH. Update to 0.15.8 once released.
> Fix rfc6492 interop (AKI format) #948

- Cargo.lock
- Cargo.toml
- README.md
- src/daemon/mq.rs
Due to merge and release 0.12.0 on 31 October
> Merge release 0.12.0

- src/commons/eventsourcing/locks.rs
- src/commons/eventsourcing/mod.rs
- src/commons/eventsourcing/store.rs
- src/commons/eventsourcing/wal.rs
- src/test.rs
- tests/benchmark.rs
Was cherry picked from and reviewed in the prep-0.13.0 branch
> Use handle locks in WalStore. (fixes #974)

- Cargo.lock
- Cargo.toml
- README.md
- src/commons/eventsourcing/locks.rs
- src/commons/eventsourcing/mod.rs
- src/commons/eventsourcing/store.rs
- src/commons/eventsourcing/wal.rs
- src/commons/util/httpclient.rs
- src/daemon/config.rs
- src/daemon/http/server.rs
- src/test.rs
- tests/benchmark.rs
- tests/functional_roas.rs
- tests/migrate_repository.rs
> Prepare release 0.12.1

- .github/workflows/pkg.yml
> Upgrade to Ploutos v6.

- src/daemon/http/server.rs
My Zabbix server noticed an error in the /metrics endpoint :)
> Fix prometheus type for krill_cas_bgp_roas_total

- Cargo.lock
- Cargo.toml
This PR reorders the dependency list in `Cargo.toml` alphabetically. It also does a soft `cargo update`.
> Reorder Cargo.toml (and do a soft upgrade).

- Cargo.lock
- Cargo.toml
- src/cli/client.rs
- src/commons/api/ca.rs
- src/commons/crypto/signing/signers/pkcs11/signer.rs
- src/commons/crypto/signing/signers/softsigner.rs
- src/commons/util/ext_serde.rs
- src/daemon/auth/common/session.rs
- src/daemon/auth/providers/config_file/provider.rs
- src/daemon/auth/providers/openid_connect/provider.rs
- src/daemon/config.rs
- src/daemon/http/auth.rs
- src/daemon/http/server.rs
- src/daemon/http/tls.rs
- src/daemon/krillserver.rs
- src/ta/config.rs
This PR upgrades most dependencies to their current versions. It skips anything related to Hyper, OpenID Connect, and cryptoki which will happen in separate PRs.
All upgrades that require code changes have their own individual commit for easier review.
> Upgrade most dependencies.

- src/cli/ta_client.rs
- src/daemon/config.rs
- src/ta/config.rs
Similar to #1241 except for the 0.14 branch
> Rename timing_config to ta_config and alias for 0.14

- Cargo.lock
- Cargo.toml
It seems like the fslock dependency is not used anywhere so it can be removed.
> Remove fslock dependency

- Cargo.lock
- src/commons/api/rrdp.rs
- src/pubd/repository.rs
This PR update dependencies and fixes compile errors resulting from changes in the uuid crate.
> Update dependencies and fix resulting uuid-related errors.

- src/server/pubd/rrdp.rs
This PR fixes an field name change in a struct that turned out to be used in stored state date.
> Revert a field name change in the repo content store.

- src/daemon/http/dispatch/root.rs
This PR fixes the redirect from `/` to `/ui` and allows subpaths of `/ui`.
> Fix redirect from / and fix handling of /ui paths.

- src/commons/storage/backends/disk.rs
This PR uses a buffered writer when writing and serialising data which should further improve performance.
> Use a BufWriter for writing to disk store.
